### ISSUE TITLE
Relationship between deposit data and age

### ISSUE THREAD

**Issue by akikuya** [sunericd/svz_singlecell_aging_clocks#1]
Thank you for wonderful dataset. I have downloaded fastq files from ENA under the accession PRJNA795276. However, I'm unsure which files correspond to which Age. Could you please provide clarification?

**Comment by sunericd** [comment]
You should be able to link fastq to batch using the biosample information. (Screenshot 1)
![image](https://github.com/sunericd/svz_singlecell_aging_clocks/assets/7906731/5e8b5b22-fa54-42a4-a7ea-5b7c1e8f8479)

Then you can demultiplex the fastq files. Refer to Supplementary Table 1 for sequences (Screenshot 2). Then you’ll have to use a demultiplexing tool such as CITE-seq-Count bash [tool](https://hoohm.github.io/CITE-seq-Count/Running-the-script/) to demux in a compute cluster.
![image](https://github.com/sunericd/svz_singlecell_aging_clocks/assets/7906731/b53abb70-1f1e-4f99-a4fc-8fe8f610d3b2)


You can map ages using the Supplementary Table 1 metadata as well.
